# Generated by Django 3.0.8 on 2020-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=9)),
                ('complement', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=8)),
                ('description', models.TextField(max_length=255)),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
