# Generated by Django 3.0.8 on 2020-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
